/*
 * Сервис аккаунтов
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.practicum.cash.account.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * Результаты вызова и информация о пользователе
 */
@JsonPropertyOrder({
  UserInfoRs.JSON_PROPERTY_USER_INFO,
  UserInfoRs.JSON_PROPERTY_RESPONSE_INFO
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-17T11:33:15.955470100+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.12.0")
public class UserInfoRs {
  public static final String JSON_PROPERTY_USER_INFO = "userInfo";
  @jakarta.annotation.Nullable
  private UserInfo userInfo;

  public static final String JSON_PROPERTY_RESPONSE_INFO = "responseInfo";
  @jakarta.annotation.Nonnull
  private ResponseInfo responseInfo;

  public UserInfoRs() {
  }

  public UserInfoRs userInfo(@jakarta.annotation.Nullable UserInfo userInfo) {
    
    this.userInfo = userInfo;
    return this;
  }

  /**
   * Get userInfo
   * @return userInfo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserInfo getUserInfo() {
    return userInfo;
  }


  @JsonProperty(JSON_PROPERTY_USER_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserInfo(@jakarta.annotation.Nullable UserInfo userInfo) {
    this.userInfo = userInfo;
  }

  public UserInfoRs responseInfo(@jakarta.annotation.Nonnull ResponseInfo responseInfo) {
    
    this.responseInfo = responseInfo;
    return this;
  }

  /**
   * Get responseInfo
   * @return responseInfo
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESPONSE_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResponseInfo getResponseInfo() {
    return responseInfo;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponseInfo(@jakarta.annotation.Nonnull ResponseInfo responseInfo) {
    this.responseInfo = responseInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserInfoRs userInfoRs = (UserInfoRs) o;
    return Objects.equals(this.userInfo, userInfoRs.userInfo) &&
        Objects.equals(this.responseInfo, userInfoRs.responseInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userInfo, responseInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserInfoRs {\n");
    sb.append("    userInfo: ").append(toIndentedString(userInfo)).append("\n");
    sb.append("    responseInfo: ").append(toIndentedString(responseInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

