/*
 * Сервис аккаунтов
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.practicum.cash.account.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Информация о пользователе
 */
@JsonPropertyOrder({
  UserInfo.JSON_PROPERTY_ID,
  UserInfo.JSON_PROPERTY_USERNAME,
  UserInfo.JSON_PROPERTY_PASSWORD,
  UserInfo.JSON_PROPERTY_FULL_NAME,
  UserInfo.JSON_PROPERTY_BIRTH_DAY,
  UserInfo.JSON_PROPERTY_EMAIL,
  UserInfo.JSON_PROPERTY_ROLES,
  UserInfo.JSON_PROPERTY_ACCOUNTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-17T11:33:15.955470100+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.12.0")
public class UserInfo {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_USERNAME = "username";
  @jakarta.annotation.Nonnull
  private String username;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @jakarta.annotation.Nonnull
  private String password;

  public static final String JSON_PROPERTY_FULL_NAME = "fullName";
  @jakarta.annotation.Nonnull
  private String fullName;

  public static final String JSON_PROPERTY_BIRTH_DAY = "birthDay";
  @jakarta.annotation.Nonnull
  private LocalDate birthDay = null;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @jakarta.annotation.Nonnull
  private String email;

  public static final String JSON_PROPERTY_ROLES = "roles";
  @jakarta.annotation.Nonnull
  private List<String> roles = new ArrayList<>();

  public static final String JSON_PROPERTY_ACCOUNTS = "accounts";
  @jakarta.annotation.Nonnull
  private List<AccountDetailInfo> accounts = new ArrayList<>();

  public UserInfo() {
  }

  public UserInfo id(@jakarta.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * уникальный идентификатор пользователя
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public UserInfo username(@jakarta.annotation.Nonnull String username) {
    
    this.username = username;
    return this;
  }

  /**
   * уникальное имя пользователя
   * @return username
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsername(@jakarta.annotation.Nonnull String username) {
    this.username = username;
  }

  public UserInfo password(@jakarta.annotation.Nonnull String password) {
    
    this.password = password;
    return this;
  }

  /**
   * зашифрованный пароль пользователя
   * @return password
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPassword(@jakarta.annotation.Nonnull String password) {
    this.password = password;
  }

  public UserInfo fullName(@jakarta.annotation.Nonnull String fullName) {
    
    this.fullName = fullName;
    return this;
  }

  /**
   * полное имя пользователя
   * @return fullName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFullName() {
    return fullName;
  }


  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFullName(@jakarta.annotation.Nonnull String fullName) {
    this.fullName = fullName;
  }

  public UserInfo birthDay(@jakarta.annotation.Nonnull LocalDate birthDay) {
    
    this.birthDay = birthDay;
    return this;
  }

  /**
   * точная дата рождения пользователя
   * @return birthDay
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BIRTH_DAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getBirthDay() {
    return birthDay;
  }


  @JsonProperty(JSON_PROPERTY_BIRTH_DAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBirthDay(@jakarta.annotation.Nonnull LocalDate birthDay) {
    this.birthDay = birthDay;
  }

  public UserInfo email(@jakarta.annotation.Nonnull String email) {
    
    this.email = email;
    return this;
  }

  /**
   * почта пользователя
   * @return email
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(@jakarta.annotation.Nonnull String email) {
    this.email = email;
  }

  public UserInfo roles(@jakarta.annotation.Nonnull List<String> roles) {
    
    this.roles = roles;
    return this;
  }

  public UserInfo addRolesItem(String rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<>();
    }
    this.roles.add(rolesItem);
    return this;
  }

  /**
   * Get roles
   * @return roles
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ROLES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getRoles() {
    return roles;
  }


  @JsonProperty(JSON_PROPERTY_ROLES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoles(@jakarta.annotation.Nonnull List<String> roles) {
    this.roles = roles;
  }

  public UserInfo accounts(@jakarta.annotation.Nonnull List<AccountDetailInfo> accounts) {
    
    this.accounts = accounts;
    return this;
  }

  public UserInfo addAccountsItem(AccountDetailInfo accountsItem) {
    if (this.accounts == null) {
      this.accounts = new ArrayList<>();
    }
    this.accounts.add(accountsItem);
    return this;
  }

  /**
   * Get accounts
   * @return accounts
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<AccountDetailInfo> getAccounts() {
    return accounts;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccounts(@jakarta.annotation.Nonnull List<AccountDetailInfo> accounts) {
    this.accounts = accounts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserInfo userInfo = (UserInfo) o;
    return Objects.equals(this.id, userInfo.id) &&
        Objects.equals(this.username, userInfo.username) &&
        Objects.equals(this.password, userInfo.password) &&
        Objects.equals(this.fullName, userInfo.fullName) &&
        Objects.equals(this.birthDay, userInfo.birthDay) &&
        Objects.equals(this.email, userInfo.email) &&
        Objects.equals(this.roles, userInfo.roles) &&
        Objects.equals(this.accounts, userInfo.accounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, username, password, fullName, birthDay, email, roles, accounts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserInfo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    birthDay: ").append(toIndentedString(birthDay)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    accounts: ").append(toIndentedString(accounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

