/*
 * Сервис работы с переводами между счетами
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.practicum.front.transfer.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Запрос на перевод средств между счетами
 */
@JsonPropertyOrder({
  TransferCashRq.JSON_PROPERTY_FROM_ACCOUNT,
  TransferCashRq.JSON_PROPERTY_TO_ACCOUNT,
  TransferCashRq.JSON_PROPERTY_VALUE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-17T11:33:00.206339600+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.12.0")
public class TransferCashRq {
  public static final String JSON_PROPERTY_FROM_ACCOUNT = "fromAccount";
  @jakarta.annotation.Nullable
  private String fromAccount;

  public static final String JSON_PROPERTY_TO_ACCOUNT = "toAccount";
  @jakarta.annotation.Nullable
  private String toAccount;

  public static final String JSON_PROPERTY_VALUE = "value";
  @jakarta.annotation.Nullable
  private BigDecimal value;

  public TransferCashRq() {
  }

  public TransferCashRq fromAccount(@jakarta.annotation.Nullable String fromAccount) {
    
    this.fromAccount = fromAccount;
    return this;
  }

  /**
   * счет источник
   * @return fromAccount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROM_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFromAccount() {
    return fromAccount;
  }


  @JsonProperty(JSON_PROPERTY_FROM_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromAccount(@jakarta.annotation.Nullable String fromAccount) {
    this.fromAccount = fromAccount;
  }

  public TransferCashRq toAccount(@jakarta.annotation.Nullable String toAccount) {
    
    this.toAccount = toAccount;
    return this;
  }

  /**
   * счет получатель
   * @return toAccount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TO_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToAccount() {
    return toAccount;
  }


  @JsonProperty(JSON_PROPERTY_TO_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToAccount(@jakarta.annotation.Nullable String toAccount) {
    this.toAccount = toAccount;
  }

  public TransferCashRq value(@jakarta.annotation.Nullable BigDecimal value) {
    
    this.value = value;
    return this;
  }

  /**
   * сумма средств
   * @return value
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@jakarta.annotation.Nullable BigDecimal value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferCashRq transferCashRq = (TransferCashRq) o;
    return Objects.equals(this.fromAccount, transferCashRq.fromAccount) &&
        Objects.equals(this.toAccount, transferCashRq.toAccount) &&
        Objects.equals(this.value, transferCashRq.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromAccount, toAccount, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferCashRq {\n");
    sb.append("    fromAccount: ").append(toIndentedString(fromAccount)).append("\n");
    sb.append("    toAccount: ").append(toIndentedString(toAccount)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

