/*
 * Сервис работы с наличными средствами
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.practicum.front.cash.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Запрос на внесение / снятие наличных средств со счета
 */
@JsonPropertyOrder({
  ChangeCashRq.JSON_PROPERTY_ACTION,
  ChangeCashRq.JSON_PROPERTY_USER_NAME,
  ChangeCashRq.JSON_PROPERTY_CURRENCY,
  ChangeCashRq.JSON_PROPERTY_VALUE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-17T11:32:59.974439300+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.12.0")
public class ChangeCashRq {
  public static final String JSON_PROPERTY_ACTION = "action";
  @jakarta.annotation.Nonnull
  private String action;

  public static final String JSON_PROPERTY_USER_NAME = "userName";
  @jakarta.annotation.Nonnull
  private String userName;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private String currency;

  public static final String JSON_PROPERTY_VALUE = "value";
  @jakarta.annotation.Nonnull
  private BigDecimal value;

  public ChangeCashRq() {
  }

  public ChangeCashRq action(@jakarta.annotation.Nonnull String action) {
    
    this.action = action;
    return this;
  }

  /**
   * желаемое действие - внести или снять
   * @return action
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAction() {
    return action;
  }


  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAction(@jakarta.annotation.Nonnull String action) {
    this.action = action;
  }

  public ChangeCashRq userName(@jakarta.annotation.Nonnull String userName) {
    
    this.userName = userName;
    return this;
  }

  /**
   * логин пользователя
   * @return userName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserName() {
    return userName;
  }


  @JsonProperty(JSON_PROPERTY_USER_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserName(@jakarta.annotation.Nonnull String userName) {
    this.userName = userName;
  }

  public ChangeCashRq currency(@jakarta.annotation.Nonnull String currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * валюта счета
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
  }

  public ChangeCashRq value(@jakarta.annotation.Nonnull BigDecimal value) {
    
    this.value = value;
    return this;
  }

  /**
   * количество средств
   * @return value
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValue(@jakarta.annotation.Nonnull BigDecimal value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangeCashRq changeCashRq = (ChangeCashRq) o;
    return Objects.equals(this.action, changeCashRq.action) &&
        Objects.equals(this.userName, changeCashRq.userName) &&
        Objects.equals(this.currency, changeCashRq.currency) &&
        Objects.equals(this.value, changeCashRq.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, userName, currency, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangeCashRq {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

