/*
 * Сервис работы с уведомлениями
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.practicum.cash.notification.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * Запрос на отправку уведомления
 */
@JsonPropertyOrder({
  SendNotificationRq.JSON_PROPERTY_USER_MAIL,
  SendNotificationRq.JSON_PROPERTY_SUBJECT,
  SendNotificationRq.JSON_PROPERTY_TEXT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-17T11:33:16.283603800+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.12.0")
public class SendNotificationRq {
  public static final String JSON_PROPERTY_USER_MAIL = "userMail";
  @jakarta.annotation.Nonnull
  private String userMail;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @jakarta.annotation.Nonnull
  private String subject;

  public static final String JSON_PROPERTY_TEXT = "text";
  @jakarta.annotation.Nonnull
  private String text;

  public SendNotificationRq() {
  }

  public SendNotificationRq userMail(@jakarta.annotation.Nonnull String userMail) {
    
    this.userMail = userMail;
    return this;
  }

  /**
   * почта пользователя
   * @return userMail
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_MAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserMail() {
    return userMail;
  }


  @JsonProperty(JSON_PROPERTY_USER_MAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserMail(@jakarta.annotation.Nonnull String userMail) {
    this.userMail = userMail;
  }

  public SendNotificationRq subject(@jakarta.annotation.Nonnull String subject) {
    
    this.subject = subject;
    return this;
  }

  /**
   * тема уведомления
   * @return subject
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSubject() {
    return subject;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@jakarta.annotation.Nonnull String subject) {
    this.subject = subject;
  }

  public SendNotificationRq text(@jakarta.annotation.Nonnull String text) {
    
    this.text = text;
    return this;
  }

  /**
   * текст уведомления
   * @return text
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setText(@jakarta.annotation.Nonnull String text) {
    this.text = text;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendNotificationRq sendNotificationRq = (SendNotificationRq) o;
    return Objects.equals(this.userMail, sendNotificationRq.userMail) &&
        Objects.equals(this.subject, sendNotificationRq.subject) &&
        Objects.equals(this.text, sendNotificationRq.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userMail, subject, text);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendNotificationRq {\n");
    sb.append("    userMail: ").append(toIndentedString(userMail)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

