/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.yandex.practicum.cash.cash.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import ru.yandex.practicum.cash.cash.model.ChangeCashRq;
import ru.yandex.practicum.cash.cash.model.ResponseInfo;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-17T11:33:15.766305700+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.12.0")
@Validated
@Tag(name = "cash", description = "the cash API")
public interface CashApi {

    /**
     * POST /cash/update : Внести или снять наличные средства со счета
     * Сервис получает запрос на зачисление или снятие средств. Выполняется обращение к account-service, blocker-service, notification-service
     *
     * @param changeCashRq  (optional)
     * @return OK (status code 200)
     *         or BAD REQUEST (status code 400)
     */
    @Operation(
        operationId = "updateCash",
        summary = "Внести или снять наличные средства со счета",
        description = "Сервис получает запрос на зачисление или снятие средств. Выполняется обращение к account-service, notification-service",
        tags = { "cash" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseInfo.class))
            }),
            @ApiResponse(responseCode = "400", description = "BAD REQUEST", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseInfo.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/cash/update",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ResponseInfo> updateCash(
        @Parameter(name = "ChangeCashRq", description = "") @Valid @RequestBody(required = false) ChangeCashRq changeCashRq
    );

}
