/*
 * Сервис аккаунтов
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.practicum.front.account.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Краткая информация о пользователе
 */
@JsonPropertyOrder({
  ShortUserInfo.JSON_PROPERTY_USERNAME,
  ShortUserInfo.JSON_PROPERTY_FULL_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-17T11:32:59.505686100+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.12.0")
public class ShortUserInfo {
  public static final String JSON_PROPERTY_USERNAME = "username";
  @jakarta.annotation.Nonnull
  private String username;

  public static final String JSON_PROPERTY_FULL_NAME = "fullName";
  @jakarta.annotation.Nonnull
  private String fullName;

  public ShortUserInfo() {
  }

  public ShortUserInfo username(@jakarta.annotation.Nonnull String username) {
    
    this.username = username;
    return this;
  }

  /**
   * уникальное имя пользователя
   * @return username
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsername(@jakarta.annotation.Nonnull String username) {
    this.username = username;
  }

  public ShortUserInfo fullName(@jakarta.annotation.Nonnull String fullName) {
    
    this.fullName = fullName;
    return this;
  }

  /**
   * полное имя пользователя
   * @return fullName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFullName() {
    return fullName;
  }


  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFullName(@jakarta.annotation.Nonnull String fullName) {
    this.fullName = fullName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShortUserInfo shortUserInfo = (ShortUserInfo) o;
    return Objects.equals(this.username, shortUserInfo.username) &&
        Objects.equals(this.fullName, shortUserInfo.fullName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, fullName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShortUserInfo {\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

