/*
 * Сервис аккаунтов
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.practicum.front.account.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Запрос на перевод денег между счетами пользователей
 */
@JsonPropertyOrder({
  TransferCashRq.JSON_PROPERTY_FROM_ACCOUNT,
  TransferCashRq.JSON_PROPERTY_FROM_ACCOUNT_VALUE,
  TransferCashRq.JSON_PROPERTY_TO_ACCOUNT,
  TransferCashRq.JSON_PROPERTY_TO_USER,
  TransferCashRq.JSON_PROPERTY_TO_ACCOUNT_VALUE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-17T11:32:59.505686100+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.12.0")
public class TransferCashRq {
  public static final String JSON_PROPERTY_FROM_ACCOUNT = "fromAccount";
  @jakarta.annotation.Nullable
  private String fromAccount;

  public static final String JSON_PROPERTY_FROM_ACCOUNT_VALUE = "fromAccountValue";
  @jakarta.annotation.Nullable
  private BigDecimal fromAccountValue;

  public static final String JSON_PROPERTY_TO_ACCOUNT = "toAccount";
  @jakarta.annotation.Nullable
  private String toAccount;

  public static final String JSON_PROPERTY_TO_USER = "toUser";
  @jakarta.annotation.Nullable
  private String toUser;

  public static final String JSON_PROPERTY_TO_ACCOUNT_VALUE = "toAccountValue";
  @jakarta.annotation.Nullable
  private BigDecimal toAccountValue;

  public TransferCashRq() {
  }

  public TransferCashRq fromAccount(@jakarta.annotation.Nullable String fromAccount) {
    
    this.fromAccount = fromAccount;
    return this;
  }

  /**
   * счет, с которого необходимо списать
   * @return fromAccount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROM_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFromAccount() {
    return fromAccount;
  }


  @JsonProperty(JSON_PROPERTY_FROM_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromAccount(@jakarta.annotation.Nullable String fromAccount) {
    this.fromAccount = fromAccount;
  }

  public TransferCashRq fromAccountValue(@jakarta.annotation.Nullable BigDecimal fromAccountValue) {
    
    this.fromAccountValue = fromAccountValue;
    return this;
  }

  /**
   * сумма, которую необходимо списать
   * @return fromAccountValue
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROM_ACCOUNT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getFromAccountValue() {
    return fromAccountValue;
  }


  @JsonProperty(JSON_PROPERTY_FROM_ACCOUNT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromAccountValue(@jakarta.annotation.Nullable BigDecimal fromAccountValue) {
    this.fromAccountValue = fromAccountValue;
  }

  public TransferCashRq toAccount(@jakarta.annotation.Nullable String toAccount) {
    
    this.toAccount = toAccount;
    return this;
  }

  /**
   * счет, на который необходимо зачислить
   * @return toAccount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TO_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToAccount() {
    return toAccount;
  }


  @JsonProperty(JSON_PROPERTY_TO_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToAccount(@jakarta.annotation.Nullable String toAccount) {
    this.toAccount = toAccount;
  }

  public TransferCashRq toUser(@jakarta.annotation.Nullable String toUser) {
    
    this.toUser = toUser;
    return this;
  }

  /**
   * логин пользователя, которому выполняется перевод
   * @return toUser
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TO_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToUser() {
    return toUser;
  }


  @JsonProperty(JSON_PROPERTY_TO_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToUser(@jakarta.annotation.Nullable String toUser) {
    this.toUser = toUser;
  }

  public TransferCashRq toAccountValue(@jakarta.annotation.Nullable BigDecimal toAccountValue) {
    
    this.toAccountValue = toAccountValue;
    return this;
  }

  /**
   * сумма, которую необходимо зачислить
   * @return toAccountValue
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TO_ACCOUNT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getToAccountValue() {
    return toAccountValue;
  }


  @JsonProperty(JSON_PROPERTY_TO_ACCOUNT_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToAccountValue(@jakarta.annotation.Nullable BigDecimal toAccountValue) {
    this.toAccountValue = toAccountValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferCashRq transferCashRq = (TransferCashRq) o;
    return Objects.equals(this.fromAccount, transferCashRq.fromAccount) &&
        Objects.equals(this.fromAccountValue, transferCashRq.fromAccountValue) &&
        Objects.equals(this.toAccount, transferCashRq.toAccount) &&
        Objects.equals(this.toUser, transferCashRq.toUser) &&
        Objects.equals(this.toAccountValue, transferCashRq.toAccountValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromAccount, fromAccountValue, toAccount, toUser, toAccountValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferCashRq {\n");
    sb.append("    fromAccount: ").append(toIndentedString(fromAccount)).append("\n");
    sb.append("    fromAccountValue: ").append(toIndentedString(fromAccountValue)).append("\n");
    sb.append("    toAccount: ").append(toIndentedString(toAccount)).append("\n");
    sb.append("    toUser: ").append(toIndentedString(toUser)).append("\n");
    sb.append("    toAccountValue: ").append(toIndentedString(toAccountValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

