/*
 * Сервис аккаунтов
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.practicum.front.account.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Информация о пользователе к обновлению
 */
@JsonPropertyOrder({
  UpdateUserInfoRq.JSON_PROPERTY_PASSWORD,
  UpdateUserInfoRq.JSON_PROPERTY_FULL_NAME,
  UpdateUserInfoRq.JSON_PROPERTY_BIRTH_DAY,
  UpdateUserInfoRq.JSON_PROPERTY_EMAIL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-17T11:32:59.505686100+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.12.0")
public class UpdateUserInfoRq {
  public static final String JSON_PROPERTY_PASSWORD = "password";
  @jakarta.annotation.Nullable
  private String password;

  public static final String JSON_PROPERTY_FULL_NAME = "fullName";
  @jakarta.annotation.Nullable
  private String fullName;

  public static final String JSON_PROPERTY_BIRTH_DAY = "birthDay";
  @jakarta.annotation.Nullable
  private LocalDate birthDay = null;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @jakarta.annotation.Nullable
  private String email;

  public UpdateUserInfoRq() {
  }

  public UpdateUserInfoRq password(@jakarta.annotation.Nullable String password) {
    
    this.password = password;
    return this;
  }

  /**
   * зашифрованный пароль пользователя
   * @return password
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(@jakarta.annotation.Nullable String password) {
    this.password = password;
  }

  public UpdateUserInfoRq fullName(@jakarta.annotation.Nullable String fullName) {
    
    this.fullName = fullName;
    return this;
  }

  /**
   * полное имя пользователя
   * @return fullName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFullName() {
    return fullName;
  }


  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullName(@jakarta.annotation.Nullable String fullName) {
    this.fullName = fullName;
  }

  public UpdateUserInfoRq birthDay(@jakarta.annotation.Nullable LocalDate birthDay) {
    
    this.birthDay = birthDay;
    return this;
  }

  /**
   * точная дата рождения пользователя
   * @return birthDay
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BIRTH_DAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getBirthDay() {
    return birthDay;
  }


  @JsonProperty(JSON_PROPERTY_BIRTH_DAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBirthDay(@jakarta.annotation.Nullable LocalDate birthDay) {
    this.birthDay = birthDay;
  }

  public UpdateUserInfoRq email(@jakarta.annotation.Nullable String email) {
    
    this.email = email;
    return this;
  }

  /**
   * почта пользователя
   * @return email
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@jakarta.annotation.Nullable String email) {
    this.email = email;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateUserInfoRq updateUserInfoRq = (UpdateUserInfoRq) o;
    return Objects.equals(this.password, updateUserInfoRq.password) &&
        Objects.equals(this.fullName, updateUserInfoRq.fullName) &&
        Objects.equals(this.birthDay, updateUserInfoRq.birthDay) &&
        Objects.equals(this.email, updateUserInfoRq.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(password, fullName, birthDay, email);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateUserInfoRq {\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    birthDay: ").append(toIndentedString(birthDay)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

